### ISSUE TITLE
operate metrics

### ISSUE THREAD

**Issue by wyukawa** [prometheus-junkyard/prometheus_cli#13]
if prometheus_cli has the feature to operate(for example, delete) metrics, I think that it is useful.

Usecase example is https://groups.google.com/forum/#!topic/prometheus-developers/lN8SxTsiaWU

Another usecase example is my experience.

When I implemented the following exporters, I wanted to change metrics name. but it was a little difficult to use HTTP API.

https://github.com/wyukawa/jstat_exporter
https://github.com/wyukawa/hadoop_exporter

**Comment by beorn7** [comment]
This will not be implemented in prometheus_cli. It can be considered for promtool once it has querying abilities.
See https://github.com/prometheus/prometheus/issues/1605
