### ISSUE TITLE
Deprecate and move to prometheus-junkyard…

### ISSUE THREAD

**Issue by beorn7** [prometheus-junkyard/prometheus_cli#14]
…once https://github.com/prometheus/prometheus/issues/1605 is done.

**Comment by beorn7** [comment]
Since the CLI will not work with Prometheus 1.0.0 anymore, we should move it to the junkyard right now, even without the querying functionality in promtool.

@brian-brazil @fabxc Any objections?

**Comment by brian-brazil** [comment]
sgtm

**Comment by beorn7** [comment]
I'll move this over now and send an announcement mail.
