### ISSUE TITLE
Rename to cli

### ISSUE THREAD

**Issue by grobie** [prometheus-junkyard/prometheus_cli#4]
None of the other repositories is prefixed.

**Comment by juliusv** [comment]
Guess we can do this, but we have to make sure that the resulting binary will still be named "prometheus_cli" (or similar), not just "cli".

**Comment by juliusv** [comment]
The Makefile would ensure that, but not if someone builds using just "go build". Hm.

**Comment by beorn7** [comment]
prometheus_cli is deprecated. Once the new way (that doesn't work yet, cf. https://github.com/prometheus/prometheus/issues/1605) is implemented, it will be junkyarded, so no reason to work on this issue.
